app_info:
    name: github.com/itmo-education/delivery-backend
    version: v0.0.7
    startup_duration: 10s
data_sources:
  - resource_name: sqlite
    path: /app/call-a-courier.db
server:
    - name: rest
      port: 8080
environment: {}
